//CRIAR OBJETO
POST http://localhost:3333/motor
Content-Type: application/json

{
    "potencia": "300 cavalos",
    "cilindro": 6,
    "tamanho": 450
}

###
//VISUALIZAR
GET http://localhost:3333/motor

###
//FILTRO
GET http://localhost:3333/motor?search=300

###
//ATUALIZAR
PUT http://localhost:3333/motor/
Content-Type: application/json

{
    "potencia": "230 cavalos",
    "cilindro": 4,
    "tamanho": 310
}

###
//DELETAR
DELETE http://localhost:3333/motor/
