//CRIAR OBJETOS 2
POST http://localhost:3333/motor
Content-Type: application/json

{
    "potencia": "300 cavalos",
    "cilindro": 6,
    "tamanho": 450
}

###
//VISUALIZAR CÓDIGO
GET http://localhost:3333/motor

###
//FILTRO PESQUISAR
GET http://localhost:3333/motor?search=300

###
//ATUALIZAR C/ID DO PUT
PUT http://localhost:3333/motor/
Content-Type: application/json

{
    "potencia": "230 cavalos",
    "cilindro": 4,
    "tamanho": 310
}

###
//DELETAR C/ID
DELETE http://localhost:3333/motor/
